### ISSUE TITLE
Zpětná vazba

### ISSUE THREAD

**Issue by ifischerova** [Klatnik/PROJEKT-Kontakty#1]
Ahoj Katko,

díky za odevzdání, líbí se mi to :)

Tipy  na úpravy:
- `align-items: center;` se dá zapnout až od tabletu, v mobilní verzi to zdá se nic nedělá. 
- `padding-left: 0;` co máš nastavený v PC breakpointu na `.zena`, by asi měl být u selektoru `.text`?
- Pozor na dvouslovné názvy class v HTML bez pomlčky, interpetuje se to jako dvě classy. Co koukám do CSS, tak tak to "jedna", "dva" atd. nemáš nějak definované, takže to chápu tak, že to má jenom od sebe odlišit jednotlivé "kontakty". Myslím ale, že v tomto příkladu mezi jednotlivými kontakty nemusíš dělat nějaké rozdíly, budou se stylovat všechny stejně.
- misto `overflow:hidden;`, které tam je asi proto, aby zabránilo vytíkání textu z kartičky (?), ale vlastně ten text mizí, by mělo stačit dát obrázkům `max-width: 40%;` a obrázky se začnou zmenšovat, když bude potřeba, ale obsah zůstane v kartě. 

Co je zamýšlené, že by mělo dělat `min-width: 0;` v `.zena` v mobilní verzi? V tuhle chvíli to asi nic nedělá.

**Comment by Klatnik** [comment]
Ahoj, vše už mám snad opraveno. `align-items: center;` jsem tam měla proto, aby se obrázky neroztahovaly. Dala jsem tam místo toho  `align-items: normal;`  a už se neroztahují :) - snad je to teď víc sémanticky správně.

**Comment by ifischerova** [comment]
Ahoj, bezva  👍
